version: "3.7"

volumes:
  db:

services:
  app:
    build:
      dockerfile: build/Dockerfile
      context: .
    ports:
      - 8080:8080
    volumes:
      - .env:/fio/.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:16"
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 5s
      retries: 5